name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: make

    - name: archive
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          artefacts/*
        retention-days: 30
